# Generated by Django 3.2.23 on 2024-01-21 12:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240121_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='flats_owned', to='property.Owner', verbose_name='Владельцы квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
    ]
