# Generated by Django 3.2.23 on 2024-01-21 12:15

from django.db import migrations


def fill_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(name=flat.owner, pure_phone=flat.owner_pure_phone)
        owner.flats.add(flat)
        flat.owners.add(owner)

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(name=flat.owner, pure_phone=flat.owner_pure_phone)
        owner.flats.remove(flat)
        flat.owners.remove(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20240121_1513'),
    ]

    operations = [
        migrations.RunPython(fill_owner_flats, move_backward)        
    ]
