# Generated by Django 3.2.23 on 2024-01-21 12:15

from django.db import migrations


def fill_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    if flats.exists():
        for flat in flats.iterator():
            owner, created = Owner.objects.get_or_create(name=flat.owner, pure_phone=flat.owner_pure_phone)
            owner.flats.add(flat)


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    if flats.exists():
        for flat in flats.iterator():
            owner, created = Owner.objects.get_or_create(name=flat.owner, pure_phone=flat.owner_pure_phone)
            owner.flats.remove(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20240121_1513'),
    ]

    operations = [
        migrations.RunPython(fill_owner_flats, move_backward)
    ]
